# Hyperlight-Unikraft Examples
#
# Run all examples:         just run-all
# Run all 5x (w/ restore):  just run-all-5
# Rebuild + run all:        just rebuild-run-all

set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# Run each example once
run-all: (run "helloworld-c") (run "rust") (run "go") (run "shell") (run "python") (run "python-tools") (run "nodejs") (run "dotnet") (run "dotnet-nativeaot") (run "powershell")
    @echo "### ALL DONE"

# Run each example 5x (tests snapshot/restore)
run-all-5: (run-5 "helloworld-c") (run-5 "rust") (run-5 "go") (run-5 "shell") (run-5 "python") (run-5 "python-tools") (run-5 "nodejs") (run-5 "dotnet") (run-5 "dotnet-nativeaot") (run-5 "powershell")
    @echo "### ALL DONE"

# Run a single example
run name:
    @echo "### EXAMPLE: {{name}}"
    just -d {{name}} -f {{name}}/Justfile run

# Run a single example 5x
run-5 name:
    @echo "### EXAMPLE: {{name}}"
    just -d {{name}} -f {{name}}/Justfile run-5

# Rebuild all on Linux (needs kraft + docker)
rebuild-all: (rebuild "helloworld-c") (rebuild "rust") (rebuild "go") (rebuild "shell") (rebuild "python") (rebuild "python-tools") (rebuild "nodejs") (rebuild "dotnet") (rebuild "dotnet-nativeaot") (rebuild "powershell")

rebuild name:
    just -d {{name}} -f {{name}}/Justfile rebuild

rootfs-all: (rootfs "helloworld-c") (rootfs "rust") (rootfs "go") (rootfs "shell") (rootfs "python") (rootfs "python-tools") (rootfs "nodejs") (rootfs "dotnet") (rootfs "dotnet-nativeaot") (rootfs "powershell")

rootfs name:
    just -d {{name}} -f {{name}}/Justfile rootfs
